@startuml

start

:FooEventListener;
-> FooEvent;
:BarEventListener;
-> List(TarEvent, ZarEvent);
split
    -> TarEvent;
    :TarEventListener;
    -> ZarEvent;
    split
        :ZarEventListener;
        end
        split again
        :ZarEventSecondListener;
        end
    end split
split again
    -> ZarEvent;
    split
    :ZarEventListener;
    end
    split again
    :ZarEventSecondListener;
    end
    end split
end split

start
   :EventListener;
   note right: Listens for all events
end

@enduml