@startuml

start

:FooEventListener;
-> FooEvent;
:BarEventListener;
-> List(TarEvent, ZarEvent);
split
    -> TarEvent;
    :TarEventListener;
    -> ZarEvent;
    :ZarEventListener;
    end
split again
    -> ZarEvent;
    :ZarEventListener;
    end
end split

start
   :EventListener;
   note right: Listens for all events
end

@enduml